### ISSUE TITLE
suggestion: setup a discord channel?

### ISSUE THREAD

**Issue by tomhsiao1260** [RedstoneYZ/RedstoneYZ#1]
嗨 抱歉打擾

我是圖學課知道這個專案，覺得蠻有趣的，感覺你們會繼續做一陣子，之後有打算開一個 dc 嗎？

**Comment by Zollo757347** [comment]
哈囉，抱歉目前我們還沒有開 Discord 的想法，如果你有興趣想協作的話歡迎開 issue 或 PR 來。不過目前的大架構都已經差不多建立好了，所以希望不要有太多的大改動。

**Comment by tomhsiao1260** [comment]
嗨 謝謝回覆 只是單純想 follow 一下這個專案 看看之後的進展

另外，我看到 yohe 有修 ric 的課，其實他兒子也對 minecraft 實作很感興趣，順便貼上來，也許你們會有興趣
https://shaoruu.io/
https://discord.gg/RfpyYffg

**Comment by Zollo757347** [comment]
這個人好強，謝謝你的資訊，我會好好膜拜他的程式。
